#ifndef MICROPY_INCLUDED_SHARED_BINDINGS_SIMPLEFOC___INIT___H
#define MICROPY_INCLUDED_SHARED_BINDINGS_SIMPLEFOC___INIT___H

// SimpleFOC module - Motor control algorithms for CircuitPython

#endif // MICROPY_INCLUDED_SHARED_BINDINGS_SIMPLEFOC___INIT___H
